#!/bin/sh


unset BUILD_BASE_NAME
unset BUILD_ARCHIVE_ROOT

unset DEPLOY_ROOT
unset DEPLOY_CONTEXT_PATH
unset DEPLOY_PORT
unset DEPLOY_JPDA_PORT
unset DEPLOY_SHUTDOWN_PORT
unset DEPLOY_REDIRECT_PORT

unset INTERFACE_BUNDLE
unset INTERFACE_DEPLOY_BUNDLE
unset INTERFACE_STD_DEPLOY_BUNDLE

unset SRC_MAVEN_ARCHIVE
unset SRC_JDK_ARCHIVE
unset SRC_CATALINA_ARCHIVE
unset SRC_MAVEN_SETTINGS
unset SRC_CATALINA_SERVER_TEMPLATE

unset MAVEN_SETTINGS

unset JAVA_HOME
unset CLASSPATH
unset MAVEN_HOME

unset CATALINA_HOME
unset CATALINA_BASE
unset CATALINA_LOG
unset LOG

unset GIT_BIN
